#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
gotcha_dir="$repo_root/docs/gotchas"
index_file="$gotcha_dir/INDEX.md"
row_file="$(mktemp)"
trap 'rm -f "$row_file"' EXIT

shopt -s nullglob
for gotcha_file in "$gotcha_dir"/GOTCHA-*.md; do
    front_matter="$(awk '/^---[[:space:]]*$/{count++; if(count==2) exit; next} count==1{print}' "$gotcha_file")"
    [[ -n "$front_matter" ]] || { echo "missing front matter: $gotcha_file" >&2; exit 1; }
    field() {
        awk -v key="$1" '$0 ~ "^" key ":" {sub("^" key ":[[:space:]]*", ""); print; exit}' <<<"$front_matter"
    }
    scope="$(awk '/^scope:/{inside=1; next} inside && /^[[:space:]]*- /{sub(/^[[:space:]]*- /, ""); values[++count]=$0; next} inside && /^[^[:space:]]/{inside=0} END{for(i=1;i<=count;i++) printf "%s%s", values[i], (i<count?", ":"")}' <<<"$front_matter")"
    title="$(awk '/^# /{sub(/^# /, ""); print; exit}' "$gotcha_file")"
    printf '| [%s](%s) | %s | %s | %s | %s | %s |\n' \
        "$(field id)" "$(basename "$gotcha_file")" "$title" "$(field severity)" \
        "$(field status)" "$scope" "$(field discovered)" >>"$row_file"
done

{
    printf '%s\n\n' '# Gotchas index'
    printf '%s\n\n' '> Auto-generated by `scripts/gotchas-index.sh`. Do not edit by hand.'
    printf '%s\n' '| ID | Title | Severity | Status | Scope | Discovered |'
    printf '%s\n' '|---|---|---|---|---|---|'
    if [[ -s "$row_file" ]]; then sort -V "$row_file"; else printf '%s\n' '| _none yet_ | | | | | |'; fi
} >"$index_file"

echo "wrote $index_file"
